### ISSUE TITLE
Discuss UI Mockups

### ISSUE THREAD

**Issue by Diaga** [MLH-Fellowship/CodeVidLive#12]
Keeping in mind the use cases mentioned in #1, we should discuss the UI/workflow before actually getting into code, so that, everyone has an idea what's the end product is going to be.

I will write down how the application looks in my head and we can either iterate on that or the team can come up with another approach.

The idea is to make the UI heavily focused on only one page, so the user does not have to navigate through all the screens. Something like Uber's UI ![Uber Redesign Example](https://miro.medium.com/max/3240/1*rH-eSUly_v_xZbVXfM9zzw.jpeg)**Disclaimer**: All credits for the picture to this [article](https://uxplanet.org/uber-redesign-concept-2019-3d8c430f6c29)

Briefly, it would be a main map screen with a bottom modal sheet (Flutter widget term). We can go over the specifics if everyone agrees.
I believe @michiboo wants to work on the maps. What do you think?

**Comment by michiboo** [comment]
I think it's a good idea but with a simpler bottom and less options. Probably for now just a button that share user location, more can be add later. What do you think

**Comment by RashikaKarki** [comment]
That's a great idea and it will be user friendly too. But I have a concern, will there be other visualization except for the map, if we are going to add more visualization then only one page UI may be less feasible. But if not that would be great.

**Comment by RashikaKarki** [comment]
Please do give this a check #18

**Comment by Diaga** [comment]
Moved to #18.
