### ISSUE TITLE
Setting up Web Crawler

### ISSUE THREAD

**Issue by RashikaKarki** [MLH-Fellowship/CodeVidLive#15]
If we are setting up the web crawler to replace the dummy data(for the US) then I think we could set up a crawler in this [page](https://www.worldometers.info/coronavirus/country/us/) and we will be able to get real-time data to some extent. But I did not find a way to work around the past data and it seems that we can only get data on the state level. 
Any alternatives for this?

**Comment by zzj0402** [comment]
Data model: https://github.com/MLH-Fellowship/CodeVidLive/issues/8

**Comment by michiboo** [comment]
Closing this issue as we decided use open sourced data set instead of crawling for data 
Further discussion at #30
