### ISSUE TITLE
Logo Design 

### ISSUE THREAD

**Issue by michiboo** [MLH-Fellowship/CodeVidLive#45]
@RashikaKarki  @zzj0402  @Diaga  Guys I generate some Logo design, see which one do you like.

![Screenshot from 2020-06-05 09-49-45](https://user-images.githubusercontent.com/26637492/83827946-0c8c6980-a712-11ea-84cb-1fbe15605d18.png)
![Screenshot from 2020-06-05 09-49-22](https://user-images.githubusercontent.com/26637492/83827949-0dbd9680-a712-11ea-8978-4a5b733a2f23.png)
![Screenshot from 2020-06-05 09-48-50](https://user-images.githubusercontent.com/26637492/83827956-101ff080-a712-11ea-8314-f1e0ec1c5fdf.png)

**Comment by Diaga** [comment]
I liked the bottom right most.

Here, I have one too.
![splash](https://user-images.githubusercontent.com/38937684/83828157-74828600-a6f9-11ea-86ed-cbc3c11ec006.png)

**Comment by michiboo** [comment]
@Diaga Cool I like your one better!
