### ISSUE TITLE
C3 visualization for flutter

### ISSUE THREAD

**Issue by zzj0402** [MLH-Fellowship/CodeVidLive#6]
https://pub.dev/packages/c3

**Comment by RashikaKarki** [comment]
For the visualization, I have used [charts_flutter](https://pub.dev/packages/charts_flutter) package as it had for interactive components.

### Progress:
- [X] Make Bar chart with dummy data
- [X] Added BottomSheet for the Visualization
- [ ] Explore other visualization
- [ ] Replace Dummy data with real data
