### ISSUE TITLE
Covid 19 case dataset with geo locations

### ISSUE THREAD

**Issue by zzj0402** [MLH-Fellowship/CodeVidLive#8]
Crawl news and merge?
Checking out existing Covid Data on Kaggle

**Comment by Diaga** [comment]
I think we can take an existing Covid Dataset on Kaggle that has city level details of confirmed cases, and then create a dummy column using random locations from Maps. 
Later on, we can crawl news and replace dummy data for real time detection.

Does that make sense? @zzj0402

**Comment by zzj0402** [comment]
Yes, it does.

**Comment by zzj0402** [comment]
## User
### ID
### Tested? Boolean
### Confirmed? Boolean
### Location? (Float,Float) Coordinate
### Current City
### Timeline? https://www.google.com/maps/timeline?pb

**Comment by Diaga** [comment]
[China District Level CSV](https://github.com/beoutbreakprepared/nCoV2019/blob/master/covid19/data/clean-outside-hubei.csv)
I will be using this dataset for models in #30.

Moving discussion to above mentioned issue and closing this.
